set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    BROTRACKER_ARKOS_SYSROOT)

if(NOT DEFINED BROTRACKER_ARKOS_SYSROOT OR
   BROTRACKER_ARKOS_SYSROOT STREQUAL "")
    message(FATAL_ERROR
        "Set BROTRACKER_ARKOS_SYSROOT to an extracted ArkOS ARM64 root filesystem")
endif()

set(CMAKE_SYSROOT "${BROTRACKER_ARKOS_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${BROTRACKER_ARKOS_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Compile-only probes defer executable linking until the real target build.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
